// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	corev1 "k8s.io/api/core/v1"

	schema "k8s.io/apimachinery/pkg/runtime/schema"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetScale provides a mock function with given fields: ctx, gvr, namespace, name
func (_m *Client) GetScale(ctx context.Context, gvr schema.GroupVersionResource, namespace string, name string) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, gvr, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetScale")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, schema.GroupVersionResource, string, string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, gvr, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, schema.GroupVersionResource, string, string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, gvr, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, schema.GroupVersionResource, string, string) error); ok {
		r1 = rf(ctx, gvr, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetScale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScale'
type Client_GetScale_Call struct {
	*mock.Call
}

// GetScale is a helper method to define mock.On call
//   - ctx context.Context
//   - gvr schema.GroupVersionResource
//   - namespace string
//   - name string
func (_e *Client_Expecter) GetScale(ctx interface{}, gvr interface{}, namespace interface{}, name interface{}) *Client_GetScale_Call {
	return &Client_GetScale_Call{Call: _e.mock.On("GetScale", ctx, gvr, namespace, name)}
}

func (_c *Client_GetScale_Call) Run(run func(ctx context.Context, gvr schema.GroupVersionResource, namespace string, name string)) *Client_GetScale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(schema.GroupVersionResource), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Client_GetScale_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *Client_GetScale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetScale_Call) RunAndReturn(run func(context.Context, schema.GroupVersionResource, string, string) (*unstructured.Unstructured, error)) *Client_GetScale_Call {
	_c.Call.Return(run)
	return _c
}

// ListNamespaces provides a mock function with given fields: ctx, selector
func (_m *Client) ListNamespaces(ctx context.Context, selector string) (*corev1.NamespaceList, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for ListNamespaces")
	}

	var r0 *corev1.NamespaceList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*corev1.NamespaceList, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *corev1.NamespaceList); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.NamespaceList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNamespaces'
type Client_ListNamespaces_Call struct {
	*mock.Call
}

// ListNamespaces is a helper method to define mock.On call
//   - ctx context.Context
//   - selector string
func (_e *Client_Expecter) ListNamespaces(ctx interface{}, selector interface{}) *Client_ListNamespaces_Call {
	return &Client_ListNamespaces_Call{Call: _e.mock.On("ListNamespaces", ctx, selector)}
}

func (_c *Client_ListNamespaces_Call) Run(run func(ctx context.Context, selector string)) *Client_ListNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_ListNamespaces_Call) Return(_a0 *corev1.NamespaceList, _a1 error) *Client_ListNamespaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListNamespaces_Call) RunAndReturn(run func(context.Context, string) (*corev1.NamespaceList, error)) *Client_ListNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkloads provides a mock function with given fields: ctx, gvr, namespace, selector
func (_m *Client) ListWorkloads(ctx context.Context, gvr schema.GroupVersionResource, namespace string, selector string) (*unstructured.UnstructuredList, error) {
	ret := _m.Called(ctx, gvr, namespace, selector)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkloads")
	}

	var r0 *unstructured.UnstructuredList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, schema.GroupVersionResource, string, string) (*unstructured.UnstructuredList, error)); ok {
		return rf(ctx, gvr, namespace, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, schema.GroupVersionResource, string, string) *unstructured.UnstructuredList); ok {
		r0 = rf(ctx, gvr, namespace, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.UnstructuredList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, schema.GroupVersionResource, string, string) error); ok {
		r1 = rf(ctx, gvr, namespace, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkloads'
type Client_ListWorkloads_Call struct {
	*mock.Call
}

// ListWorkloads is a helper method to define mock.On call
//   - ctx context.Context
//   - gvr schema.GroupVersionResource
//   - namespace string
//   - selector string
func (_e *Client_Expecter) ListWorkloads(ctx interface{}, gvr interface{}, namespace interface{}, selector interface{}) *Client_ListWorkloads_Call {
	return &Client_ListWorkloads_Call{Call: _e.mock.On("ListWorkloads", ctx, gvr, namespace, selector)}
}

func (_c *Client_ListWorkloads_Call) Run(run func(ctx context.Context, gvr schema.GroupVersionResource, namespace string, selector string)) *Client_ListWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(schema.GroupVersionResource), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Client_ListWorkloads_Call) Return(_a0 *unstructured.UnstructuredList, _a1 error) *Client_ListWorkloads_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListWorkloads_Call) RunAndReturn(run func(context.Context, schema.GroupVersionResource, string, string) (*unstructured.UnstructuredList, error)) *Client_ListWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateScale provides a mock function with given fields: ctx, gvr, namespace, scaleObj
func (_m *Client) UpdateScale(ctx context.Context, gvr schema.GroupVersionResource, namespace string, scaleObj *unstructured.Unstructured) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, gvr, namespace, scaleObj)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScale")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, schema.GroupVersionResource, string, *unstructured.Unstructured) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, gvr, namespace, scaleObj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, schema.GroupVersionResource, string, *unstructured.Unstructured) *unstructured.Unstructured); ok {
		r0 = rf(ctx, gvr, namespace, scaleObj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, schema.GroupVersionResource, string, *unstructured.Unstructured) error); ok {
		r1 = rf(ctx, gvr, namespace, scaleObj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_UpdateScale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateScale'
type Client_UpdateScale_Call struct {
	*mock.Call
}

// UpdateScale is a helper method to define mock.On call
//   - ctx context.Context
//   - gvr schema.GroupVersionResource
//   - namespace string
//   - scaleObj *unstructured.Unstructured
func (_e *Client_Expecter) UpdateScale(ctx interface{}, gvr interface{}, namespace interface{}, scaleObj interface{}) *Client_UpdateScale_Call {
	return &Client_UpdateScale_Call{Call: _e.mock.On("UpdateScale", ctx, gvr, namespace, scaleObj)}
}

func (_c *Client_UpdateScale_Call) Run(run func(ctx context.Context, gvr schema.GroupVersionResource, namespace string, scaleObj *unstructured.Unstructured)) *Client_UpdateScale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(schema.GroupVersionResource), args[2].(string), args[3].(*unstructured.Unstructured))
	})
	return _c
}

func (_c *Client_UpdateScale_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *Client_UpdateScale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_UpdateScale_Call) RunAndReturn(run func(context.Context, schema.GroupVersionResource, string, *unstructured.Unstructured) (*unstructured.Unstructured, error)) *Client_UpdateScale_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
