branches:
- name: main
  channel: "next"
  prerelease: "rc"
- name: "v+([0-9])"
  channel: "latest"
- name: "release/v+([0-9]).+([0-9])"
  range: "${name.replace('release/v', '') + '.x'}"
  channel: "${name.replace('release/v', '')}"

# Until the https://github.com/semantic-release/semantic-release/issues/1487 is resolved,
# we workaround by using a prerelease branch for the main branch,
# and latest stable branch for with major version as transition.
tagFormat: "v${version}"

plugins:
- [
    "@semantic-release/commit-analyzer",
    {
      "preset": "conventionalcommits",
      "releaseRules": [
        {"scope": "charts", "release": false},
        {"type": "feat", "release": "minor"},
        {"type": "fix", "release": "patch"},
        {"type": "perf", "release": "patch"}
      ]
    }
  ]
- [
    "@semantic-release/release-notes-generator",
    {
      "preset": "conventionalcommits",
      "presetConfig": {
        "scope": [
          "api",
          "cmd",
          "controller",
          "deps",
          "executor",
          "scheduler",
          "test"
        ],
        "types": [
          { "type": "feat", "section": "✨ Features", "hidden": false },
          { "type": "fix", "section": "🐛 Bug Fixes", "hidden": false },
          { "type": "perf", "section": "🚀 Performance Improvements", "hidden": false },
          { "type": "chore", "section": "🧹 Miscellaneous", "hidden": false }
        ]
      }
    }
  ]
- [
    "@semantic-release/exec",
    {
      "generateNotesCmd": "./hack/sync-version.sh ${nextRelease.version} app",
      "publishCmd": "make build-dist VERSION=${nextRelease.version}",
      "successCmd": "./hack/create-maintenance-branch.sh ${nextRelease.version}",
    }
  ]
- [
    "@semantic-release/git",
    {
      "assets": [
        "charts/hibernator/Chart.yaml",
        "charts/hibernator/README.md"
      ],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n${nextRelease.notes}"
    }
  ]
- [
    "@semantic-release/github",
    {
      "assets": [
        {
          "path": "dist/kubectl-hibernator/**/kubectl-hibernator-*",
        },
      ]
    }
  ]
