tagFormat: "v${version}"

plugins:
- [
    "./.github/releaserc/plugins/scope-filter.cjs",
    {
      "excludeScopes": ["charts", "release"],
    }
  ]
- [
    "@semantic-release/commit-analyzer",
    {
      "preset": "conventionalcommits",
      "releaseRules": [
        {"type": "feat", "release": "minor"},
        {"type": "fix", "release": "patch"},
        {"type": "perf", "release": "patch"}
      ]
    }
  ]
- [
    "@semantic-release/release-notes-generator",
    {
      "preset": "conventionalcommits",
      "presetConfig": {
        "types": [
          {"type": "feat", "section": "✨ Features", "hidden": false},
          {"type": "fix", "section": "🐛 Bug Fixes", "hidden": false},
          {"type": "perf", "section": "🚀 Performance Improvements", "hidden": false},
          {"type": "chore", "section": "🧹 Miscellaneous", "hidden": false},
          {"type": "refactor", "section": "🛠️ Code Refactoring", "hidden": false}
        ]
      }
    }
  ]
- [
    "@semantic-release/exec",
    {
      "verifyReleaseCmd": "./hack/verify-release.sh ${nextRelease.type}",
      "generateNotesCmd": "./hack/sync-version.sh ${nextRelease.version} app",
      "publishCmd": "make build-dist VERSION=${nextRelease.version}",
      "successCmd": "./hack/post-release-branch.sh ${nextRelease.version}"
    }
  ]
- [
    "@semantic-release/git",
    {
      "assets": [
        "charts/hibernator/Chart.yaml",
        "charts/hibernator/README.md"
      ],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n${nextRelease.notes}"
    }
  ]
- [
    "@semantic-release/github",
    {
      "assets": [
        {
          "path": "dist/kubectl-hibernator/**/kubectl-hibernator-*",
        },
      ]
    }
  ]
