branches:
- "main"

tagFormat: "chart-v${version}"

plugins:
- [
    "./.github/releaserc/plugins/scope-filter.cjs",
    {
      "scopes": ["charts"],
      "filterOutMissingScope": true
    }
  ]
- [
    "@semantic-release/commit-analyzer",
    {
      "preset": "conventionalcommits",
      "releaseRules": [
        {"type": "feat", "release": "minor"},
        {"type": "fix", "release": "patch"}
      ]
    }
  ]
- [
    "@semantic-release/release-notes-generator",
    {
      "preset": "conventionalcommits",
      "presetConfig": {
        "types": [
          {"type": "feat", "section": "✨ Features", "hidden": false},
          {"type": "fix", "section": "🐛 Bug Fixes", "hidden": false},
          {"type": "chore", "section": "🧹 Miscellaneous", "hidden": false}
        ]
      }
    }
  ]
- [
    "@semantic-release/exec",
    {
      "generateNotesCmd": "./hack/sync-version.sh ${nextRelease.version} chart"
    }
  ]
- [
    "@semantic-release/git",
    {
      "assets": [
        "charts/hibernator/Chart.yaml",
        "charts/hibernator/README.md"
      ],
      "message": "chore(charts): ${nextRelease.version} [skip ci]\n${nextRelease.notes}"
    }
  ]
