// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dynamic "k8s.io/client-go/dynamic"

	mock "github.com/stretchr/testify/mock"

	schema "k8s.io/apimachinery/pkg/runtime/schema"

	v1 "k8s.io/api/core/v1"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// ListNode provides a mock function with given fields: ctx, selector
func (_m *Client) ListNode(ctx context.Context, selector string) (*v1.NodeList, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for ListNode")
	}

	var r0 *v1.NodeList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1.NodeList, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.NodeList); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.NodeList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resource provides a mock function with given fields: gvr
func (_m *Client) Resource(gvr schema.GroupVersionResource) dynamic.NamespaceableResourceInterface {
	ret := _m.Called(gvr)

	if len(ret) == 0 {
		panic("no return value specified for Resource")
	}

	var r0 dynamic.NamespaceableResourceInterface
	if rf, ok := ret.Get(0).(func(schema.GroupVersionResource) dynamic.NamespaceableResourceInterface); ok {
		r0 = rf(gvr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamic.NamespaceableResourceInterface)
		}
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
