// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dynamic "k8s.io/client-go/dynamic"

	mock "github.com/stretchr/testify/mock"

	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// K8sClient is an autogenerated mock type for the K8sClient type
type K8sClient struct {
	mock.Mock
}

// Resource provides a mock function with given fields: gvr
func (_m *K8sClient) Resource(gvr schema.GroupVersionResource) dynamic.NamespaceableResourceInterface {
	ret := _m.Called(gvr)

	if len(ret) == 0 {
		panic("no return value specified for Resource")
	}

	var r0 dynamic.NamespaceableResourceInterface
	if rf, ok := ret.Get(0).(func(schema.GroupVersionResource) dynamic.NamespaceableResourceInterface); ok {
		r0 = rf(gvr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamic.NamespaceableResourceInterface)
		}
	}

	return r0
}

// NewK8sClient creates a new instance of K8sClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewK8sClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *K8sClient {
	mock := &K8sClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
