/*
Copyright 2026 Ardika Saputro.
Licensed under the Apache License, Version 2.0.
*/

package scheduler

import (
	"fmt"
	"strings"
	"time"

	"github.com/robfig/cron/v3"
	"k8s.io/utils/clock"
)

// ExceptionType defines the type of schedule exception.
type ExceptionType string

const (
	// ExceptionExtend adds hibernation windows to the base schedule.
	ExceptionExtend ExceptionType = "extend"
	// ExceptionSuspend prevents hibernation during specified windows (carve-out).
	ExceptionSuspend ExceptionType = "suspend"
	// ExceptionReplace completely replaces the base schedule during the exception period.
	ExceptionReplace ExceptionType = "replace"
)

// Exception represents a schedule exception for evaluation.
type Exception struct {
	// Type is the exception type: extend, suspend, or replace.
	Type ExceptionType

	// ValidFrom is when the exception period starts.
	ValidFrom time.Time

	// ValidUntil is when the exception period ends.
	ValidUntil time.Time

	// LeadTime is the buffer before suspension (only for suspend type).
	LeadTime time.Duration

	// Windows are the exception time windows.
	Windows []OffHourWindow
}

// ScheduleEvaluator evaluates cron-based schedules to determine hibernation state.
type ScheduleEvaluator struct {
	Clock clock.Clock

	parser         cron.Parser
	scheduleBuffer time.Duration
}

type ScheduleEvaluatorOption func(*ScheduleEvaluator)

// NewCronParser returns a cron parser with the same configuration used by ScheduleEvaluator.
// This is useful for external callers that need to parse cron expressions generated by ParseWindowToCron.
func NewCronParser() cron.Parser {
	return cron.NewParser(cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow)
}

// NewScheduleEvaluator creates a new schedule evaluator.
func NewScheduleEvaluator(clk clock.Clock, opts ...ScheduleEvaluatorOption) *ScheduleEvaluator {
	se := &ScheduleEvaluator{
		Clock: clk,
		// Use standard cron format with optional seconds
		parser: cron.NewParser(cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow),
	}

	for _, o := range opts {
		o(se)
	}

	return se
}

func WithScheduleBuffer(duration string) ScheduleEvaluatorOption {
	return func(se *ScheduleEvaluator) {
		d, err := time.ParseDuration(duration)
		if err != nil {
			return
		}

		se.scheduleBuffer = d
	}
}

// GetScheduleBuffer returns the configured schedule buffer duration.
// This is used by external callers (e.g., provider) that need to apply
// the same buffer when computing absolute event timestamps.
func (e *ScheduleEvaluator) GetScheduleBuffer() time.Duration {
	return e.scheduleBuffer
}

// EvaluationResult contains the result of schedule evaluation.
type EvaluationResult struct {
	// ShouldHibernate indicates if the system should be in hibernation state.
	ShouldHibernate bool

	// NextHibernateTime is the next scheduled hibernation time.
	NextHibernateTime time.Time

	// NextWakeUpTime is the next scheduled wake-up time.
	NextWakeUpTime time.Time

	// CurrentState describes the current state based on schedule.
	CurrentState string

	// InGracePeriod indicates if the result was influenced by a grace period buffer.
	InGracePeriod bool

	// GracePeriodEnd is when the current grace period ends.
	GracePeriodEnd time.Time
}

// eval determines if we should be in hibernation based on the schedule.
// It compares the last hibernate and wake-up times to determine current state.
//
// The function also applies grace periods (lead time buffer) to prevent unnecessary
// phase transitions at window boundaries for minimal windows (e.g., 23:59-00:00).
func (e *ScheduleEvaluator) eval(window ScheduleWindow) (*EvaluationResult, error) {
	now := e.Clock.Now()
	loc, err := time.LoadLocation(window.Timezone)
	if err != nil {
		return nil, fmt.Errorf("invalid timezone %s: %w", window.Timezone, err)
	}

	localNow := now.In(loc)

	// Parse cron expressions
	hibernateSched, err := e.parser.Parse(window.HibernateCron)
	if err != nil {
		return nil, fmt.Errorf("invalid hibernate cron %q: %w", window.HibernateCron, err)
	}

	wakeUpSched, err := e.parser.Parse(window.WakeUpCron)
	if err != nil {
		return nil, fmt.Errorf("invalid wakeUp cron %q: %w", window.WakeUpCron, err)
	}

	// Find the most recent hibernate and wake-up times before now
	lastHibernate := e.findLastOccurrence(hibernateSched, localNow)
	lastWakeUp := e.findLastOccurrence(wakeUpSched, localNow)

	// Determine current state by comparing which event happened more recently
	shouldHibernate := lastHibernate.After(lastWakeUp)

	// Calculate next occurrences
	nextHibernate := hibernateSched.Next(localNow)
	nextWakeUp := wakeUpSched.Next(localNow)

	var (
		inGracePeriod  bool
		gracePeriodEnd time.Time
	)

	if e.scheduleBuffer > 0 {
		// Check for Start Boundary Grace Period
		// We only apply this if we are NOT in a continuous hibernation scenario.
		// If the previous window's end grace period overlaps with or touches the current window's start,
		// we should remain hibernated instead of forcing a wake-up for the grace period.
		prevWindowEndGrace := lastWakeUp.Add(e.scheduleBuffer)
		isContinuous := !prevWindowEndGrace.Before(lastHibernate)

		if shouldHibernate && !isContinuous && isInGraceTimeWindow(StartBoundary, window.Windows, localNow, e.scheduleBuffer) {
			shouldHibernate = false
			inGracePeriod = true
			gracePeriodEnd = lastHibernate.Add(e.scheduleBuffer)

			// Adjust nextHibernate to ensure composition functions (like evaluateExtend)
			// pick up the correct next event time even if InGracePeriod flag is lost.
			if gracePeriodEnd.Before(nextHibernate) {
				nextHibernate = gracePeriodEnd
			}

		} else if !shouldHibernate && isInGraceTimeWindow(EndBoundary, window.Windows, localNow, e.scheduleBuffer) {
			shouldHibernate = true
			inGracePeriod = true
			gracePeriodEnd = lastWakeUp.Add(e.scheduleBuffer)

			// Adjust nextWakeUp to ensure composition functions (like evaluateExtend)
			// pick up the correct next event time even if InGracePeriod flag is lost.
			if gracePeriodEnd.Before(nextWakeUp) {
				nextWakeUp = gracePeriodEnd
			}

		}
	}

	state := "active"
	if shouldHibernate {
		state = "hibernated"
	}

	return &EvaluationResult{
		ShouldHibernate:   shouldHibernate,
		NextHibernateTime: nextHibernate,
		NextWakeUpTime:    nextWakeUp,
		CurrentState:      state,
		InGracePeriod:     inGracePeriod,
		GracePeriodEnd:    gracePeriodEnd,
	}, nil
}

// findLastOccurrence finds the most recent occurrence of a schedule before the given time.
// It works by stepping back in time and finding when the schedule would have last fired.
func (e *ScheduleEvaluator) findLastOccurrence(sched cron.Schedule, now time.Time) time.Time {
	// Start from 24 hours ago and find the next occurrence
	// Keep stepping forward until we pass 'now', then return the previous occurrence
	searchStart := now.Add(-24 * time.Hour)

	var lastOccurrence time.Time
	current := sched.Next(searchStart)

	for current.Before(now) || current.Equal(now) {
		lastOccurrence = current
		current = sched.Next(current)
	}

	// If we didn't find any occurrence in the last 24 hours, search further back
	if lastOccurrence.IsZero() {
		searchStart = now.Add(-7 * 24 * time.Hour)
		current = sched.Next(searchStart)
		for current.Before(now) || current.Equal(now) {
			lastOccurrence = current
			current = sched.Next(current)
		}
	}

	return lastOccurrence
}

// NextRequeueTime calculates when the controller should next check the schedule.
// Returns the earlier of: next hibernate time or next wake-up time.
func (e *ScheduleEvaluator) NextRequeueTime(result *EvaluationResult) time.Duration {
	now := e.Clock.Now()
	safetyBuffer := 10 * time.Second

	if result.InGracePeriod {
		duration := result.GracePeriodEnd.Sub(now)
		if duration < 0 {
			duration = 0
		}

		// When in grace period, the next event is the end of the buffer.
		// Since we are already in the buffer, we just need the remaining time + safety.
		return duration + safetyBuffer
	}

	var nextEvent time.Time
	if result.ShouldHibernate {
		// Currently hibernated, next event is wake-up
		nextEvent = result.NextWakeUpTime
	} else {
		// Currently active, next event is hibernate
		nextEvent = result.NextHibernateTime
	}

	duration := nextEvent.Sub(now)
	if duration < 0 {
		duration = time.Minute // Safety: requeue in 1 minute if calculation is off
	}

	// Add a small buffer to ensure we're past the scheduled time
	return duration + e.scheduleBuffer + safetyBuffer
}

// Evaluate evaluates the schedule with zero or more exceptions applied.
// Multiple exceptions of the same type are merged internally (windows
// concatenated, validity expanded to the widest bounds, max LeadTime used),
// so callers may pass the raw list without pre-merging.
//
// Exception composition order: replace → extend → suspend.
//   - replace: substitutes the base schedule entirely with exception windows.
//   - extend:  unions its windows with the (possibly replaced) base.
//   - suspend: carve-out — keeps resources awake during exception windows.
//
// When both extend and suspend are present, suspend operates against the full
// hibernation set (effectiveBase ∪ extend.Windows) so it correctly sees all
// windows that could trigger hibernation.
func (e *ScheduleEvaluator) Evaluate(baseWindows []OffHourWindow, timezone string, exceptions []*Exception) (*EvaluationResult, error) {
	// Filter to only active exceptions.
	var active []*Exception
	for _, exc := range exceptions {
		if exc != nil && e.isExceptionActive(exc) {
			active = append(active, exc)
		}
	}

	if len(active) == 0 {
		return e.evaluateWindows(baseWindows, timezone)
	}

	effectiveBase := baseWindows

	// Phase 1: Replace — substitutes the base entirely.
	if rep := mergeByType(active, ExceptionReplace); rep != nil {
		effectiveBase = rep.Windows
	}

	ext := mergeByType(active, ExceptionExtend)
	sus := mergeByType(active, ExceptionSuspend)

	switch {
	case ext != nil && sus != nil:
		// Evaluate the extended schedule (base ∪ extend windows) via evaluateExtend,
		// then overlay the suspend carve-out — including lead-time and grace-period
		// logic — on top of that result via applySuspendCarveOut.
		extResult, err := e.evaluateExtend(effectiveBase, ext.Windows, timezone)
		if err != nil {
			return nil, err
		}
		return e.applySuspendCarveOut(extResult, sus, timezone)

	case ext != nil:
		return e.evaluateExtend(effectiveBase, ext.Windows, timezone)

	case sus != nil:
		return e.evaluateSuspend(effectiveBase, sus, timezone)

	default:
		// Only replace (already applied) — evaluate the effective base.
		return e.evaluateWindows(effectiveBase, timezone)
	}
}

// mergeByType collects all exceptions of the given type and merges them into a
// single logical exception. Windows are concatenated, validity is expanded to
// the widest bounds, and LeadTime uses the maximum. Returns nil if no exception
// of this type exists.
func mergeByType(exceptions []*Exception, t ExceptionType) *Exception {
	var matches []*Exception
	for _, exc := range exceptions {
		if exc.Type == t {
			matches = append(matches, exc)
		}
	}

	if len(matches) == 0 {
		return nil
	}
	if len(matches) == 1 {
		return matches[0]
	}

	merged := &Exception{
		Type:       t,
		ValidFrom:  matches[0].ValidFrom,
		ValidUntil: matches[0].ValidUntil,
	}
	for _, m := range matches {
		if m.ValidFrom.Before(merged.ValidFrom) {
			merged.ValidFrom = m.ValidFrom
		}
		if m.ValidUntil.After(merged.ValidUntil) {
			merged.ValidUntil = m.ValidUntil
		}
		merged.Windows = append(merged.Windows, m.Windows...)
		if m.LeadTime > merged.LeadTime {
			merged.LeadTime = m.LeadTime
		}
	}

	return merged
}

// applySuspendCarveOut applies suspension exception logic on top of a pre-computed
// base evaluation result. It mirrors the carve-out, lead-time, and grace-period
// handling of evaluateSuspend but uses an already-evaluated base result instead of
// re-running evaluateWindows(baseWindows). This is required for the ext+sus
// composition case: evaluateWindows iterates per-window and OR-combines results,
// so separating the extend evaluation from the suspend carve-out ensures the full
// extended schedule is preserved correctly.
func (e *ScheduleEvaluator) applySuspendCarveOut(baseResult *EvaluationResult, exception *Exception, timezone string) (*EvaluationResult, error) {
	now := e.Clock.Now()
	loc, err := time.LoadLocation(timezone)
	if err != nil {
		return nil, fmt.Errorf("invalid timezone %s: %w", timezone, err)
	}
	localNow := now.In(loc)

	if len(exception.Windows) == 0 {
		return baseResult, nil
	}

	inSuspensionWindow := isInTimeWindows(exception.Windows, localNow)

	inSuspensionGrace := false
	if !inSuspensionWindow && e.scheduleBuffer > 0 {
		inSuspensionGrace = isInGraceTimeWindow(EndBoundary, exception.Windows, localNow, e.scheduleBuffer)
	}

	inLeadTimeWindow := false
	if exception.LeadTime > 0 {
		inLeadTimeWindow = isInLeadTimeWindow(exception.Windows, localNow, exception.LeadTime)
	}

	shouldHibernate := baseResult.ShouldHibernate

	if inSuspensionWindow || inSuspensionGrace {
		shouldHibernate = false
	} else if inLeadTimeWindow && !baseResult.ShouldHibernate {
		// Not hibernating — lead time's "don't start" is a no-op here.
	} else if inLeadTimeWindow && baseResult.ShouldHibernate {
		// Only suppress if the cluster would still be hibernating when the
		// suspension window opens. If it wakes naturally before then (e.g.,
		// extend window ends at 18:00 while suspend starts at Thu 09:00), the
		// lead-time suppression is unnecessary and must be skipped.
		nextSuspStart := e.findNextSuspensionStart(exception.Windows, localNow)
		clusterWakesBeforeSusp := !nextSuspStart.IsZero() &&
			!baseResult.NextWakeUpTime.IsZero() &&
			!baseResult.NextWakeUpTime.After(nextSuspStart)
		if !clusterWakesBeforeSusp {
			shouldHibernate = false
		}
	}

	state := "active"
	if shouldHibernate {
		state = "hibernated"
	}

	nextHibernate := baseResult.NextHibernateTime
	nextWakeUp := baseResult.NextWakeUpTime

	if inSuspensionWindow || inLeadTimeWindow || inSuspensionGrace {
		suspensionEnd := e.findSuspensionEnd(exception.Windows, localNow)
		if !suspensionEnd.IsZero() && suspensionEnd.After(localNow) {
			if suspensionEnd.Before(nextHibernate) || nextHibernate.IsZero() {
				nextHibernate = suspensionEnd
			}
		}
	}

	if shouldHibernate {
		if next := e.findNextSuspensionStart(exception.Windows, localNow); !next.IsZero() {
			nextWakeUp = earlierTime(nextWakeUp, next)
		}
	}

	return &EvaluationResult{
		ShouldHibernate:   shouldHibernate,
		NextHibernateTime: nextHibernate,
		NextWakeUpTime:    nextWakeUp,
		CurrentState:      state,
		InGracePeriod:     inSuspensionGrace,
		GracePeriodEnd:    baseResult.GracePeriodEnd,
	}, nil
}

// isExceptionActive checks if the exception is currently within its valid period.
func (e *ScheduleEvaluator) isExceptionActive(exception *Exception) bool {
	now := e.Clock.Now()
	return !now.Before(exception.ValidFrom) && !now.After(exception.ValidUntil)
}

// evaluateWindows evaluates a set of OffHourWindows and returns the result.
// Each window is evaluated independently via cron and the results are
// OR-combined: hibernation is triggered when ANY window says hibernate.
// This correctly handles merged multi-exception windows (e.g., two Extend
// exceptions producing [{09:00-12:00}, {14:00-17:00}]).
func (e *ScheduleEvaluator) evaluateWindows(windows []OffHourWindow, timezone string) (*EvaluationResult, error) {
	if len(windows) == 0 {
		// No windows means no hibernation
		return &EvaluationResult{
			ShouldHibernate: false,
			CurrentState:    "active",
		}, nil
	}

	var combined *EvaluationResult
	for _, w := range windows {
		hibernateCron, wakeUpCron, err := ParseWindowToCron(w.Start, w.End, w.DaysOfWeek...)
		if err != nil {
			return nil, fmt.Errorf("convert window to cron: %w", err)
		}

		sw := ScheduleWindow{
			Windows:       []OffHourWindow{w},
			HibernateCron: hibernateCron,
			WakeUpCron:    wakeUpCron,
			Timezone:      timezone,
		}

		result, err := e.eval(sw)
		if err != nil {
			return nil, err
		}

		if combined == nil {
			combined = result
			continue
		}

		// OR-combine: hibernate if ANY window says hibernate.
		combined.ShouldHibernate = combined.ShouldHibernate || result.ShouldHibernate
		combined.NextHibernateTime = earlierTime(combined.NextHibernateTime, result.NextHibernateTime)
		combined.NextWakeUpTime = earlierTime(combined.NextWakeUpTime, result.NextWakeUpTime)
		combined.InGracePeriod = combined.InGracePeriod || result.InGracePeriod
		if result.InGracePeriod && !result.GracePeriodEnd.IsZero() {
			if combined.GracePeriodEnd.IsZero() {
				combined.GracePeriodEnd = result.GracePeriodEnd
			} else {
				combined.GracePeriodEnd = earlierTime(combined.GracePeriodEnd, result.GracePeriodEnd)
			}
		}
		if combined.ShouldHibernate {
			combined.CurrentState = "hibernated"
		}
	}

	return combined, nil
}

// evaluateExtend combines base windows with exception windows using a union (OR).
// Hibernation occurs when EITHER the base schedule OR the exception schedule says hibernate.
// Semantically, Extend adds additional hibernation windows on top of the base schedule.
// To prevent hibernation during specific windows, use the Suspend exception type instead.
func (e *ScheduleEvaluator) evaluateExtend(baseWindows, exceptionWindows []OffHourWindow, timezone string) (*EvaluationResult, error) {
	// Evaluate base schedule
	baseResult, err := e.evaluateWindows(baseWindows, timezone)
	if err != nil {
		return nil, fmt.Errorf("evaluate base windows: %w", err)
	}

	// Evaluate exception windows
	exceptionResult, err := e.evaluateWindows(exceptionWindows, timezone)
	if err != nil {
		return nil, fmt.Errorf("evaluate exception windows: %w", err)
	}

	// Hibernate when either schedule says hibernate
	shouldHibernate := baseResult.ShouldHibernate || exceptionResult.ShouldHibernate

	// Calculate next events (take the earlier of the two for each)
	nextHibernate := earlierTime(baseResult.NextHibernateTime, exceptionResult.NextHibernateTime)
	nextWakeUp := earlierTime(baseResult.NextWakeUpTime, exceptionResult.NextWakeUpTime)

	state := "active"
	if shouldHibernate {
		state = "hibernated"
	}

	// Propagate grace period if the resulting state is influenced by one.
	// For simplicity, we use the earlier grace period end if both are present.
	inGracePeriod := baseResult.InGracePeriod || exceptionResult.InGracePeriod
	var gracePeriodEnd time.Time
	if baseResult.InGracePeriod && exceptionResult.InGracePeriod {
		gracePeriodEnd = earlierTime(baseResult.GracePeriodEnd, exceptionResult.GracePeriodEnd)
	} else if baseResult.InGracePeriod {
		gracePeriodEnd = baseResult.GracePeriodEnd
	} else if exceptionResult.InGracePeriod {
		gracePeriodEnd = exceptionResult.GracePeriodEnd
	}

	return &EvaluationResult{
		ShouldHibernate:   shouldHibernate,
		NextHibernateTime: nextHibernate,
		NextWakeUpTime:    nextWakeUp,
		CurrentState:      state,
		InGracePeriod:     inGracePeriod,
		GracePeriodEnd:    gracePeriodEnd,
	}, nil
}

// evaluateSuspend evaluates schedule with suspension windows.
// Suspension PREVENTS hibernation during exception windows, even if base schedule says hibernate.
// Lead time prevents NEW hibernation starts within the buffer before suspension.
//
// NOTE: Suspend exceptions must have forward time windows (start < end).
// Backward windows (e.g., start=23:59, end=00:00) are not supported and will be logged as errors then ignored.
func (e *ScheduleEvaluator) evaluateSuspend(baseWindows []OffHourWindow, exception *Exception, timezone string) (*EvaluationResult, error) {
	now := e.Clock.Now()
	loc, err := time.LoadLocation(timezone)
	if err != nil {
		return nil, fmt.Errorf("invalid timezone %s: %w", timezone, err)
	}

	localNow := now.In(loc)

	// First evaluate base schedule
	baseResult, err := e.evaluateWindows(baseWindows, timezone)
	if err != nil {
		return nil, fmt.Errorf("evaluate base windows: %w", err)
	}

	// No special window validation needed - both forward and backward (overnight) windows are supported
	if len(exception.Windows) == 0 {
		return baseResult, nil
	}

	// Check if we're currently in a suspension window
	inSuspensionWindow := isInTimeWindows(exception.Windows, localNow)

	// Check if we're in grace period at end of suspension window
	// This fixes the boundary gap at 23:59:00 where exclusive end boundary causes suspension to be considered inactive
	inSuspensionGrace := false
	if !inSuspensionWindow && e.scheduleBuffer > 0 {
		inSuspensionGrace = isInGraceTimeWindow(EndBoundary, exception.Windows, localNow, e.scheduleBuffer)
	}

	// Check if we're in lead time window (before suspension starts)
	inLeadTimeWindow := false
	if exception.LeadTime > 0 {
		inLeadTimeWindow = isInLeadTimeWindow(exception.Windows, localNow, exception.LeadTime)
	}

	// Determine final hibernation state
	// - If in suspension window or grace period: DON'T hibernate (override base)
	// - If in lead time window AND base says start hibernating: DON'T start (but ongoing hibernation continues)
	// - Otherwise: follow base schedule
	shouldHibernate := baseResult.ShouldHibernate

	if inSuspensionWindow || inSuspensionGrace {
		// Suspension active (or in grace period) - keep awake regardless of base schedule
		shouldHibernate = false
	} else if inLeadTimeWindow && !baseResult.ShouldHibernate {
		// In lead time window but not currently hibernated
		// Don't start hibernation (will wait until after suspension)
		// Note: If already hibernated, continue hibernating until suspension window starts
	} else if inLeadTimeWindow && baseResult.ShouldHibernate {
		// In lead-time window and currently hibernating.
		// Only wake the cluster from hibernation for the lead-time if it will
		// still be hibernating when the suspension window opens. If the base
		// schedule delivers a natural wake-up before the suspension starts (e.g.,
		// extend window ends at Wed 18:00, suspension starts Thu 09:00), the
		// lead-time suppression is unnecessary and must be skipped to avoid
		// incorrectly cutting short an unrelated hibernation window.
		nextSuspStart := e.findNextSuspensionStart(exception.Windows, localNow)
		clusterWakesBeforeSusp := !nextSuspStart.IsZero() &&
			!baseResult.NextWakeUpTime.IsZero() &&
			!baseResult.NextWakeUpTime.After(nextSuspStart)
		if !clusterWakesBeforeSusp {
			shouldHibernate = false
		}
	}

	state := "active"
	if shouldHibernate {
		state = "hibernated"
	}

	// Calculate next events considering suspension
	nextHibernate := baseResult.NextHibernateTime
	nextWakeUp := baseResult.NextWakeUpTime

	// If in suspension, lead time, or grace period, we may need to adjust next hibernate time
	if inSuspensionWindow || inLeadTimeWindow || inSuspensionGrace {
		// Find when suspension ends to recalculate
		suspensionEnd := e.findSuspensionEnd(exception.Windows, localNow)
		if !suspensionEnd.IsZero() && suspensionEnd.After(localNow) {
			// Schedule check after suspension ends
			if suspensionEnd.Before(nextHibernate) || nextHibernate.IsZero() {
				nextHibernate = suspensionEnd
			}
		}
	}

	// If currently hibernating but not yet inside a suspension window, check for an upcoming
	// suspension start and pull nextWakeUp forward to that time.  Without this the controller
	// would requeue based on the base wakeup time (e.g. 18:00) and completely miss the
	// suspension transition at 09:00, leaving the system hibernated through the carve-out.
	if shouldHibernate {
		nextSuspensionStart := e.findNextSuspensionStart(exception.Windows, localNow)
		if !nextSuspensionStart.IsZero() {
			nextWakeUp = earlierTime(nextWakeUp, nextSuspensionStart)
		}
	}

	return &EvaluationResult{
		ShouldHibernate:   shouldHibernate,
		NextHibernateTime: nextHibernate,
		NextWakeUpTime:    nextWakeUp,
		CurrentState:      state,
		InGracePeriod:     inSuspensionGrace,
		GracePeriodEnd:    baseResult.GracePeriodEnd, // Use base result's grace period if applicable
	}, nil
}

// findNextSuspensionStart finds when the next suspension window will start after now.
// It checks today and tomorrow to handle cross-midnight hibernation scenarios (e.g., the
// system hibernates at 20:00 and a suspension window starts at 09:00 the following day).
func (e *ScheduleEvaluator) findNextSuspensionStart(windows []OffHourWindow, now time.Time) time.Time {
	currentTimeMinutes := now.Hour()*60 + now.Minute()

	var nextStart time.Time

	for daysAhead := 0; daysAhead <= 1; daysAhead++ {
		checkDay := now.AddDate(0, 0, daysAhead)
		checkDayStr := strings.ToUpper(checkDay.Weekday().String()[:3])

		for _, w := range windows {
			dayMatch := false
			for _, day := range w.DaysOfWeek {
				if strings.EqualFold(day, checkDayStr) {
					dayMatch = true
					break
				}
			}
			if !dayMatch {
				continue
			}

			startHour, startMin, err := parseTime(w.Start)
			if err != nil {
				continue
			}

			startMinutes := startHour*60 + startMin
			startTime := time.Date(checkDay.Year(), checkDay.Month(), checkDay.Day(), startHour, startMin, 0, 0, now.Location())

			// For today: only consider windows whose start is still in the future.
			if daysAhead == 0 && startMinutes <= currentTimeMinutes {
				continue
			}

			if nextStart.IsZero() || startTime.Before(nextStart) {
				nextStart = startTime
			}
		}
	}

	return nextStart
}

// findSuspensionEnd finds when the current or upcoming suspension window ends.
func (e *ScheduleEvaluator) findSuspensionEnd(windows []OffHourWindow, now time.Time) time.Time {
	currentDay := strings.ToUpper(now.Weekday().String()[:3])
	currentHour := now.Hour()
	currentMin := now.Minute()
	currentTimeMinutes := currentHour*60 + currentMin

	for _, w := range windows {
		// Check if today is in the window's days
		dayMatch := false
		for _, day := range w.DaysOfWeek {
			if strings.EqualFold(day, currentDay) {
				dayMatch = true
				break
			}
		}
		if !dayMatch {
			continue
		}

		// Parse window times
		startHour, startMin, err := parseTime(w.Start)
		if err != nil {
			continue
		}
		endHour, endMin, err := parseTime(w.End)
		if err != nil {
			continue
		}

		startMinutes := startHour*60 + startMin
		endMinutes := endHour*60 + endMin

		// Check if we're currently in this window
		inWindow := false
		if endMinutes > startMinutes {
			// Same-day window
			inWindow = currentTimeMinutes >= startMinutes && currentTimeMinutes < endMinutes
		} else {
			// Overnight window
			inWindow = currentTimeMinutes >= startMinutes || currentTimeMinutes < endMinutes
		}

		if inWindow {
			// Calculate when this window ends
			endTime := time.Date(now.Year(), now.Month(), now.Day(), endHour, endMin, 0, 0, now.Location())
			if endMinutes <= startMinutes && currentTimeMinutes >= startMinutes {
				// Overnight window, end is tomorrow
				endTime = endTime.Add(24 * time.Hour)
			}
			return endTime
		}
	}

	return time.Time{}
}

// ValidateCron validates a cron expression.
func (e *ScheduleEvaluator) ValidateCron(expr string) error {
	_, err := e.parser.Parse(expr)
	if err != nil {
		return fmt.Errorf("invalid cron expression %q: %w", expr, err)
	}
	return nil
}

// earlierTime returns the earlier of two times, handling zero values.
// If one time is zero, the non-zero time is returned.
// If both are zero, zero time is returned.
func earlierTime(a, b time.Time) time.Time {
	if a.IsZero() {
		return b
	}
	if b.IsZero() {
		return a
	}
	if a.Before(b) {
		return a
	}
	return b
}
