// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sts "github.com/aws/aws-sdk-go-v2/service/sts"
)

// STSClient is an autogenerated mock type for the STSClient type
type STSClient struct {
	mock.Mock
}

// AssumeRole provides a mock function with given fields: ctx, params, optFns
func (_m *STSClient) AssumeRole(ctx context.Context, params *sts.AssumeRoleInput, optFns ...func(*sts.Options)) (*sts.AssumeRoleOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AssumeRole")
	}

	var r0 *sts.AssumeRoleOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sts.AssumeRoleInput, ...func(*sts.Options)) (*sts.AssumeRoleOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sts.AssumeRoleInput, ...func(*sts.Options)) *sts.AssumeRoleOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sts.AssumeRoleOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sts.AssumeRoleInput, ...func(*sts.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSTSClient creates a new instance of STSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSTSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *STSClient {
	mock := &STSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
