// Copyright 2026 Ardika Saputro.
// Licensed under the Apache License, Version 2.0.

// Code generated by protoc-gen-go. DO NOT EDIT.
// This file is manually written to define the proto messages.
// Run `make generate-proto` to regenerate from .proto file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: api/streaming/v1alpha1/execution.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_StreamLogs_FullMethodName       = "/hibernator.v1alpha1.ExecutionService/StreamLogs"
	ExecutionService_ReportProgress_FullMethodName   = "/hibernator.v1alpha1.ExecutionService/ReportProgress"
	ExecutionService_ReportCompletion_FullMethodName = "/hibernator.v1alpha1.ExecutionService/ReportCompletion"
	ExecutionService_Heartbeat_FullMethodName        = "/hibernator.v1alpha1.ExecutionService/Heartbeat"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExecutionService handles streaming communication between runners and the control plane.
type ExecutionServiceClient interface {
	// StreamLogs streams log lines from a runner to the control plane.
	// The runner opens a client-streaming RPC and sends log entries.
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, StreamLogsResponse], error)
	// ReportProgress reports execution progress updates.
	ReportProgress(ctx context.Context, in *ProgressReport, opts ...grpc.CallOption) (*ProgressResponse, error)
	// ReportCompletion reports final execution result.
	ReportCompletion(ctx context.Context, in *CompletionReport, opts ...grpc.CallOption) (*CompletionResponse, error)
	// Heartbeat keeps the connection alive and reports runner health.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, StreamLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionService_ServiceDesc.Streams[0], ExecutionService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEntry, StreamLogsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamLogsClient = grpc.ClientStreamingClient[LogEntry, StreamLogsResponse]

func (c *executionServiceClient) ReportProgress(ctx context.Context, in *ProgressReport, opts ...grpc.CallOption) (*ProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ReportCompletion(ctx context.Context, in *CompletionReport, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ReportCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ExecutionService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// ExecutionService handles streaming communication between runners and the control plane.
type ExecutionServiceServer interface {
	// StreamLogs streams log lines from a runner to the control plane.
	// The runner opens a client-streaming RPC and sends log entries.
	StreamLogs(grpc.ClientStreamingServer[LogEntry, StreamLogsResponse]) error
	// ReportProgress reports execution progress updates.
	ReportProgress(context.Context, *ProgressReport) (*ProgressResponse, error)
	// ReportCompletion reports final execution result.
	ReportCompletion(context.Context, *CompletionReport) (*CompletionResponse, error)
	// Heartbeat keeps the connection alive and reports runner health.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) StreamLogs(grpc.ClientStreamingServer[LogEntry, StreamLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedExecutionServiceServer) ReportProgress(context.Context, *ProgressReport) (*ProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedExecutionServiceServer) ReportCompletion(context.Context, *CompletionReport) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCompletion not implemented")
}
func (UnimplementedExecutionServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutionServiceServer).StreamLogs(&grpc.GenericServerStream[LogEntry, StreamLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamLogsServer = grpc.ClientStreamingServer[LogEntry, StreamLogsResponse]

func _ExecutionService_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ReportProgress(ctx, req.(*ProgressReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ReportCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ReportCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ReportCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ReportCompletion(ctx, req.(*CompletionReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hibernator.v1alpha1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportProgress",
			Handler:    _ExecutionService_ReportProgress_Handler,
		},
		{
			MethodName: "ReportCompletion",
			Handler:    _ExecutionService_ReportCompletion_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ExecutionService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _ExecutionService_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/streaming/v1alpha1/execution.proto",
}
