// Copyright 2026 Ardika Saputro.
// Licensed under the Apache License, Version 2.0.

// Code generated by protoc-gen-go. DO NOT EDIT.
// This file is manually written to define the proto messages.
// Run `make generate-proto` to regenerate from .proto file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: api/streaming/v1alpha1/execution.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry represents a single log line from the runner.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the unique identifier for this execution.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// timestamp is when the log was generated (RFC3339).
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// level is the log level (DEBUG, INFO, WARN, ERROR).
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// message is the log content.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// fields are structured log fields.
	Fields        map[string]string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// StreamLogsResponse is the response after log streaming completes.
type StreamLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// received_count is the number of log entries received.
	ReceivedCount int64 `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *StreamLogsResponse) GetReceivedCount() int64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

// ProgressReport reports execution progress.
type ProgressReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the unique identifier for this execution.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// phase is the current execution phase.
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	// progress_percent is the estimated progress (0-100).
	ProgressPercent int32 `protobuf:"varint,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	// message describes the current activity.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// timestamp is when this progress was reported (RFC3339).
	Timestamp     string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressReport) Reset() {
	*x = ProgressReport{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressReport) ProtoMessage() {}

func (x *ProgressReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressReport.ProtoReflect.Descriptor instead.
func (*ProgressReport) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressReport) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ProgressReport) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ProgressReport) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *ProgressReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressReport) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// ProgressResponse acknowledges a progress report.
type ProgressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acknowledged indicates the progress was received.
	Acknowledged  bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ProgressResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// CompletionReport reports the final result of an execution.
type CompletionReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the unique identifier for this execution.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// success indicates whether the execution succeeded.
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains the error if success is false.
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// duration_ms is the execution duration in milliseconds.
	DurationMs int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// timestamp is when execution completed (RFC3339).
	// Note: restore_data removed - runners persist directly to ConfigMap.
	Timestamp     string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionReport) Reset() {
	*x = CompletionReport{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionReport) ProtoMessage() {}

func (x *CompletionReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionReport.ProtoReflect.Descriptor instead.
func (*CompletionReport) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *CompletionReport) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CompletionReport) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompletionReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CompletionReport) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CompletionReport) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// CompletionResponse acknowledges a completion report.
type CompletionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acknowledged indicates the completion was received.
	Acknowledged  bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *CompletionResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// HeartbeatRequest is a keep-alive message.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the unique identifier for this execution.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// timestamp is when the heartbeat was sent (RFC3339).
	Timestamp     string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// HeartbeatResponse acknowledges a heartbeat.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acknowledged indicates the heartbeat was received.
	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// server_time is the server's current time (RFC3339).
	ServerTime    string `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_streaming_v1alpha1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_streaming_v1alpha1_execution_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

var File_api_streaming_v1alpha1_execution_proto protoreflect.FileDescriptor

const file_api_streaming_v1alpha1_execution_proto_rawDesc = "" +
	"\n" +
	"&api/streaming/v1alpha1/execution.proto\x12\x13hibernator.v1alpha1\"\xf9\x01\n" +
	"\bLogEntry\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12A\n" +
	"\x06fields\x18\x05 \x03(\v2).hibernator.v1alpha1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x12StreamLogsResponse\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\x03R\rreceivedCount\"\xac\x01\n" +
	"\x0eProgressReport\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x05R\x0fprogressPercent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"6\n" +
	"\x10ProgressResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xb3\x01\n" +
	"\x10CompletionReport\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"8\n" +
	"\x12CompletionResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"S\n" +
	"\x10HeartbeatRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"X\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\tR\n" +
	"serverTime2\x88\x03\n" +
	"\x10ExecutionService\x12V\n" +
	"\n" +
	"StreamLogs\x12\x1d.hibernator.v1alpha1.LogEntry\x1a'.hibernator.v1alpha1.StreamLogsResponse(\x01\x12\\\n" +
	"\x0eReportProgress\x12#.hibernator.v1alpha1.ProgressReport\x1a%.hibernator.v1alpha1.ProgressResponse\x12b\n" +
	"\x10ReportCompletion\x12%.hibernator.v1alpha1.CompletionReport\x1a'.hibernator.v1alpha1.CompletionResponse\x12Z\n" +
	"\tHeartbeat\x12%.hibernator.v1alpha1.HeartbeatRequest\x1a&.hibernator.v1alpha1.HeartbeatResponseB7Z5github.com/ardikabs/hibernator/api/streaming/v1alpha1b\x06proto3"

var (
	file_api_streaming_v1alpha1_execution_proto_rawDescOnce sync.Once
	file_api_streaming_v1alpha1_execution_proto_rawDescData []byte
)

func file_api_streaming_v1alpha1_execution_proto_rawDescGZIP() []byte {
	file_api_streaming_v1alpha1_execution_proto_rawDescOnce.Do(func() {
		file_api_streaming_v1alpha1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_streaming_v1alpha1_execution_proto_rawDesc), len(file_api_streaming_v1alpha1_execution_proto_rawDesc)))
	})
	return file_api_streaming_v1alpha1_execution_proto_rawDescData
}

var file_api_streaming_v1alpha1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_streaming_v1alpha1_execution_proto_goTypes = []any{
	(*LogEntry)(nil),           // 0: hibernator.v1alpha1.LogEntry
	(*StreamLogsResponse)(nil), // 1: hibernator.v1alpha1.StreamLogsResponse
	(*ProgressReport)(nil),     // 2: hibernator.v1alpha1.ProgressReport
	(*ProgressResponse)(nil),   // 3: hibernator.v1alpha1.ProgressResponse
	(*CompletionReport)(nil),   // 4: hibernator.v1alpha1.CompletionReport
	(*CompletionResponse)(nil), // 5: hibernator.v1alpha1.CompletionResponse
	(*HeartbeatRequest)(nil),   // 6: hibernator.v1alpha1.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 7: hibernator.v1alpha1.HeartbeatResponse
	nil,                        // 8: hibernator.v1alpha1.LogEntry.FieldsEntry
}
var file_api_streaming_v1alpha1_execution_proto_depIdxs = []int32{
	8, // 0: hibernator.v1alpha1.LogEntry.fields:type_name -> hibernator.v1alpha1.LogEntry.FieldsEntry
	0, // 1: hibernator.v1alpha1.ExecutionService.StreamLogs:input_type -> hibernator.v1alpha1.LogEntry
	2, // 2: hibernator.v1alpha1.ExecutionService.ReportProgress:input_type -> hibernator.v1alpha1.ProgressReport
	4, // 3: hibernator.v1alpha1.ExecutionService.ReportCompletion:input_type -> hibernator.v1alpha1.CompletionReport
	6, // 4: hibernator.v1alpha1.ExecutionService.Heartbeat:input_type -> hibernator.v1alpha1.HeartbeatRequest
	1, // 5: hibernator.v1alpha1.ExecutionService.StreamLogs:output_type -> hibernator.v1alpha1.StreamLogsResponse
	3, // 6: hibernator.v1alpha1.ExecutionService.ReportProgress:output_type -> hibernator.v1alpha1.ProgressResponse
	5, // 7: hibernator.v1alpha1.ExecutionService.ReportCompletion:output_type -> hibernator.v1alpha1.CompletionResponse
	7, // 8: hibernator.v1alpha1.ExecutionService.Heartbeat:output_type -> hibernator.v1alpha1.HeartbeatResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_streaming_v1alpha1_execution_proto_init() }
func file_api_streaming_v1alpha1_execution_proto_init() {
	if File_api_streaming_v1alpha1_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_streaming_v1alpha1_execution_proto_rawDesc), len(file_api_streaming_v1alpha1_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_streaming_v1alpha1_execution_proto_goTypes,
		DependencyIndexes: file_api_streaming_v1alpha1_execution_proto_depIdxs,
		MessageInfos:      file_api_streaming_v1alpha1_execution_proto_msgTypes,
	}.Build()
	File_api_streaming_v1alpha1_execution_proto = out.File
	file_api_streaming_v1alpha1_execution_proto_goTypes = nil
	file_api_streaming_v1alpha1_execution_proto_depIdxs = nil
}
