name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - release/v*

    paths:
      - api/**
      - cmd/**
      - internal/**
      - pkg/**
      - test/**
      - go.mod

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8.0

  test-coverage:
    name: Coverage Tests
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Run Coverage Tests
        run: make test

  test-e2e:
    name: E2E Tests
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Setting up Test Dependencies
        run: make envtest

      - name: Run E2E Tests
        run: make test-e2e